### ISSUE TITLE
source code/knowledge share

### ISSUE THREAD

**Issue by lobotomy-x** [Isaiahh146/Oculus-Link-Passthrough-Home#4]
Hey I've been working with ALXR while investigating other means of achieving passthrough for PCVR and this is the first I've seen a packaged windows app do it.  I can barely even get pt over link tp work in the editor which is the only officially supported way. Did you do something hacky and perhaps thats why you havent uploaded source? In any case would you be willing to share some details

**Comment by DaryeDev** [comment]
I'd love to see how did you do this, as I'm interested in getting passthrough on my PC using Link.

**Comment by lobotomy-x** [comment]
its incredibly simple. Make an empty passthrough scene in unity or godot would even be quicker. If you don't know how you can use the oculus samples but you just need an ovrcamerarig with a passthrough layer component. Make sure in your project settings dash support is enabled. Then just build that as a development version and you'll have an exe that you can run to start passthrough. Simply open the dash UI and minimize the app menu and now you have the full oculus interface with a passthrough background. You can run other games, even VR with it open but it may still be rendering the layer underneath so it might hurt performance. Anyway really foolish of Meta to not make this the default mode

**Comment by Isaiahh146** [comment]
This is essentially all this is. It's just a very basic unity project with Oculus passthrough support.

**Comment by Isaiahh146** [comment]
> Hey I've been working with ALXR while investigating other means of achieving passthrough for PCVR and this is the first I've seen a packaged windows app do it. I can barely even get pt over link tp work in the editor which is the only officially supported way. Did you do something hacky and perhaps thats why you havent uploaded source? In any case would you be willing to share some details

It just uses the standard Oculus passthrough API. By enabling developer runtime features in the Oculus PC app and then enabling pass through over link, It allows the app to get the passthrough feed

**Comment by lobotomy-x** [comment]
yeah haha sorry I should've closed this long ago as I figured out the solution shortly after opening the thread. I think most of us just took Meta at their word when they said it only works in editor
